controller_manager:
  ros_parameters:
    update_rate: 30
    use_sim_time: true

    wheel_cont:
      type: wheel_drive_controller/WheelDriveController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

wheel_cont:
  ros__parameters:

    publish_rate: 50.0 # You can set this higher than the controller manager update rate, but it will be throttled
    base_frame_id: base_link

    left_wheel_names: ['front_left_wheel_joint' 'back_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint' 'back_right_wheel_joint']
    wheel_separation: 0.35
    wheel_radius: 0.05

    use_stamped_vel: false
