controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 100.0 
    base_frame_id: base_link

    left_wheel_names: ['front_left_wheel_joint', 'back_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint', 'back_right_wheel_joint']
    wheel_separation: 0.35
    wheel_radius: 0.05

    joints:
      - front_left_wheel_joint
      - back_left_wheel_joint
      - front_right_wheel_joint
      - back_right_wheel_joint

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity


    use_stamped_vel: false

  # open_loop: false    

   #wheels_per_side: 2
  # wheel_separation_multiplier: x
  # left_wheel_radius_multiplier: x
  # right_wheel_radius_multiplier: x

  # odom_frame_id: x
  # pose_covariance_diagonal: x
  # twist_covariance_diagonal: x
  # open_loop: x
  # enable_odom_tf: x

  # cmd_vel_timeout: x
  # publish_limited_velocity: x
  # velocity_rolling_window_size: x


  # linear.x.has_velocity_limits: false
  # linear.x.has_acceleration_limits:

    

    
