controller_manager:
  ros__parameters:
    update_rate: 50
    #use_sim_time: false

    diff_cont:
      type: diff_drive_controller/DiffDriveController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link

    right_wheel_names: [ 'front_right_wheel_joint'] #'back_right_wheel_joint',
    left_wheel_names: [ 'front_left_wheel_joint'] #'back_left_wheel_joint',
    wheel_separation: 0.35
    wheel_radius: 0.05

    joints:
      - front_right_wheel_joint
      #- back_right_wheel_joint
      - front_left_wheel_joint
      #- back_left_wheel_joint

    command_interfaces:
      - velocity

    state_interfaces:
      - velocity
      - position


    use_stamped_vel: false

    # linear.x.has_velocity_limits: false
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: 0.0
    # linear.x.min_velocity: 0.0
    # linear.x.max_acceleration: 0.0
    # linear.x.min_acceleration: 0.0
    # linear.x.max_jerk: 0.0
    # linear.x.min_jerk: 0.0

    # angular.z.has_velocity_limits: false
    # angular.z.has_acceleration_limits: false
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: 0.0
    # angular.z.min_velocity: 0.0
    # angular.z.max_acceleration: 0.0
    # angular.z.min_acceleration: 0.0
    # angular.z.max_jerk: 0.0
    # angular.z.min_jerk: 0.0

# joint_state_broadcaster:
#   ros__parameters:

    

    
